apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Reply-platform-microservice
  title: Create Reply platform microservice
  description: Create the security perimeter for the platform microservice
spec:
  owner: guest
  type: job
  parameters:
    - title: Configuration Options
      required:
        - namespace
      properties:
        namespace:
          title: Namespace
          type: string
          default: default
          description: Namespace in which this should be created
          ui:options:
            rows: 5
        clusterName:
          title: Cluster to run
          description: The cluster to run this job in. 
          type: string
          ui:field: KubernetesClusterPicker
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./templates/
        values:
          namespace: ${{ parameters.namespace }} #Parametro sostituito nel template namespace.yaml
    - id: apply-namespace
      name: apply namespace
      action: cnoe:kubernetes:apply
      input:
        manifestPath: namespace.yaml
        clusterName: ${{ parameters.clusterName }} #Parametro usato dall'action per identificare il cluster name