apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-hello-world-
  namespace: "${{values.namespace}}"
  labels:
    project_id: "${{values.project_id}}"
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      steps:
        - - name: call-whalesay-template
            templateRef:
              name: workflow-template-whalesay-template
              template: whalesay-template
            arguments:
              parameters:
                - name: message
                  value: "hello world"
