apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: "workflow-${{values.project_id}}-"
  namespace: default
  labels:
    project-id: "${{values.project_id}}"
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: main-template
            templateRef:
              name: "workflow-template-${{values.project_id}}"
              template: clone-repo
            arguments:
              parameters:
                - name: message
                  value: "hello world"