apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: "workflow-template-${{values.project_id}}"
  namespace: default
  labels:
    project-id: "${{values.project_id}}"
spec:
  workflowMetadata:
    namespace: default
    labels:
      project-id: "${{values.project_id}}"
  entrypoint: clone-repo
  onExit: on-exit
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
    - name: clone-repo
      container:
        image: alpine/git
        command: [sh, -c]
        env:
          - name: GIT_USERNAME
            valueFrom:
              secretKeyRef:
                name: user-github-tobedeleted
                key: username
          - name: GIT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: github-token
                key: password
        args:
          - |
            git clone https://$GIT_USERNAME:$(echo $GIT_PASSWORD)@github.com/CNOE-ORG-TEST/${{values.project_id}}.git
            ls -la
