apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: "workflow-template-${{values.project_id}}"
  namespace: default
  labels:
    project-id: "${{values.project_id}}"
spec:
  workflowMetadata:
    namespace: default
    labels:
      project-id: "${{values.project_id}}"
  entrypoint: main
  onExit: on-exit
  templates:
    - name: main
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: build-and-deploy-step
            template: build-and-deploy-step
            arguments: {}
    - name: build-and-deploy-step
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: 523753954008.dkr.ecr.eu-west-1.amazonaws.com/build_and_push_cnoe:0.2.2
        env:
          - name: PROJECT_ID
            value: "${{values.project_id}}"
          - name: ECR_CONTAINER_REGISTRY
            value: 523753954008.dkr.ecr.eu-west-1.amazonaws.com
        resources: {}
        securityContext:
          privileged: true
  arguments: {}
  serviceAccountName: pipeline-sa
  volumes:
    - name: workdir
      emptyDir: {}
